apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: HelmChart
      name: backstage
    patch: |-
      - op: add
        path: /valuesFile
        value: values-patch.yaml
