apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-fraud-team 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.loft.sh'
    chart: vcluster
    targetRevision: 0.35.0-alpha.3 # Pin your vcluster version
    helm:
      values: |
        # 1. Isolation Mastery: Auto-enforce Network Policies
        isolation:
          enabled: true 
          podSecurityStandard: baseline
        
        # 2. Ingress Sync: Allow tenants to expose ML models
        sync:
          ingress:
            enabled: true
          services:
            enabled: true
          nodes:
            enabled: true
            syncAllNodes: false # Don't expose our Hub's system nodes to the tenant!
            
        # 3. CoreDNS: Tenants get their own DNS for internal microservices
        coredns:
          integrated: true
  destination:
    server: 'https://kubernetes.default.svc'
    # This deploys the vcluster into a dedicated Host namespace
    namespace: host-fraud-team
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true