loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 3
  storage:
    type: s3
    s3:
      region: us-east-1
      bucketnames: platform-logs-archive
  # Ensure components land on system nodes
  read:
    nodeSelector: { platform-role: system }
  write:
    nodeSelector: { platform-role: system }

tempo:
  storage:
    trace:
      backend: s3
      s3:
        bucket: platform-traces-archive
        region: us-east-1