apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: ml-data-${{ values.teamName }}-${{ values.projectName }}
  labels:
    platform.tech/cost-center: "${{ values.costCenter }}"
spec:
  forProvider:
    region: eu-west-2
    tags:
      Team: "${{ values.teamName }}"
      CostCenter: "${{ values.costCenter }}"

---
apiVersion: database.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: ml-db-${{ values.teamName }}-${{ values.projectName }}
spec:
  forProvider:
    dbInstanceClass: db.t4g.micro
    engine: postgres
    tags:
      Team: "${{ values.teamName }}"
      CostCenter: "${{ values.costCenter }}"
  writeConnectionSecretToRef:
    name: ml-db-credentials
    namespace: host-${{ values.teamName }}