global:
  nodeSelector:
    platform-role: system
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

server:
  autoscaling:
    enabled: true
    minReplicas: 2
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - argocd-server
            topologyKey: kubernetes.io/hostname


repoServer:
  replicas: 2
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi

controller:
  replicas: 1
  resources:
    limits:
      cpu: 512m
      memory: 1Gi